### Google Colab

Colaboratory, или сокращенно Colab - это продукт компании Google Research. 
Colab позволяет любому человеку писать и выполнять произвольный код на языке python через браузер и особенно хорошо подходит для машинного обучения, анализа данных и образования. 
С технической точки зрения, Colab — это размещенный сервис Jupyter notebook, который не требует настройки для использования, но при этом предоставляет бесплатный доступ к вычислительным ресурсам, включая GPU. 
Colab можно использовать бесплатно. Ресурсы Colab не гарантированы и не безграничны, а лимиты использования иногда колеблются. Это необходимо для того, чтобы Colab мог предоставлять ресурсы бесплатно.


Блокноты Colab хранятся в Google Drive или могут быть загружены из GitHub. Блокнотами Colab можно делиться так же, как и документами Google Docs или Sheets. Просто нажмите кнопку "Поделиться" в правом верхнем углу любого блокнота Colab. Или можно скачать в формате .ipynb или .py

Виртуальная машина, которую вы используете, включая любые пользовательские файлы и библиотеки, которые вы установили, не будет использоваться совместно. Поэтому хорошей идеей будет включить код для установки и загрузки любых пользовательских библиотек или файлов, которые нужны вашему ноутбуку.

Код выполняется на виртуальной машине, являющейся частной для вашего аккаунта. Виртуальные машины удаляются после некоторого простоя и имеют максимальное время жизни, установленное службой Colab.

В бесплатной версии Colab ноутбуки могут работать не более 12 часов, в зависимости от доступности и режима использования.

https://colab.research.google.com/notebooks/markdown_guide.ipynb Руководство по разметке текста

## Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [1]:
from math import sqrt, pow
x1 = int(input("Введите число x1:"))
x2 = int(input("Введите число x2:"))
y1 = int(input("Введите число y1:"))
y2 = int(input("Введите число y2:"))
print(sqrt(pow(x1-y1,2)+pow(x2-y2,2)))

2.8284271247461903


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [2]:
def season(moth):
    global s
    if moth == 12 or 1 <= moth <= 2:
        s = 'Зима'
    if 3 <= moth <= 5:
        s = 'Весна'
    if 6 <= moth <= 8:
        s = 'Лето'
    if 9 <= moth <= 11:
        s = 'Осень'
    return s

num = int(input("Введите номер месяца: "))
k = True
while k:
    if num > 12 or num < 1:
        print("Вы ввели не существуещий номер месяца")
        num = int(input("Введите номер месяца: "))
    else:
        k = False 
season(num)
print(s)

Вы ввели не существуещий номер месяца
Вы ввели не существуещий номер месяца
Вы ввели не существуещий номер месяца
Весна


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [3]:
def is_prime(num1):
    if num1%2 == 0 and num1 != 2 or num1%3 == 0 and num1 != 3 or num1%5 == 0 and num1 != 5:
        s = False
    else:
        s = True
    return s

num = int(input("Введите число(от 0 до 1000): "))
k = True
while k:
    if num > 1000 or num < 0:
        print("Вы ввели не правильный диапозон")
        num = int(input("Введите номер месяца: "))
    else:
        k = False 
print(is_prime(num))

True


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [10]:
import random
b = []
for item in range(10):
    b.append(random.randint(0,10))
print(b)
b = b[::-1]
print(b)

[5, 7, 0, 3, 8, 4, 4, 6, 9, 4]
[4, 9, 6, 4, 4, 8, 3, 0, 7, 5]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [11]:
x = '"Привет мир!"'
print(x[3:8])

ивет 


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [5]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
 
for i in range(1, int(len(l)/2), 2):
    if not len(l) % 2:
        l[i], l[-i] = l[-i], l[i]
    else:
        l[i], l[-i-1] = l[-i-1], l[i]

**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [4]:
i =0
for i in range(500):
    if i % 7 == 0 and "8" in str(i):
        print(i, end=" ")
        i+=1

28 84 98 168 182 189 238 280 287 308 378 385 448 483 

**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [16]:
def more_than_five(lst):
    new_lst = []
    for number in lst:
        if abs(number) > 10:
            new_lst.append(number)
    return new_lst

ll = [random.randint(0,20) for item in range(10)]
print(ll)
print(more_than_five(ll))


[4, 6, 1, 17, 18, 2, 11, 2, 12, 2]
[17, 18, 11, 12]


# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [21]:

import numpy as np
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [22]:
Z = np.diag(np.arange(1, 5), k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [23]:
n = 2
a = np.random.random((3,3,3))
print(np.mean(a[:, :n], axis=1))

[[0.4295158  0.92336494 0.47347721]
 [0.51258758 0.62613866 0.79103009]
 [0.55811035 0.82289213 0.25075383]]


**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [27]:
def func_1():
    Z = np.arange(11)
    Z[(3 < Z) & (Z <= 8)] *= -1
    print(Z)

func_1()



[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [28]:
import numpy as np
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [61]:
import numpy as np

def change_str(a):
    str1 = np.random.randint(0,a.shape[0])
    str2 = np.random.randint(0,a.shape[0])
    while str1 == str2:
        str2 = np.random.randint(0,a.shape[0])

    c = np.array(a[str1])
    a[str1] = a[str2]
    a[str2] = c.data
    print(f"Меняем строку {str1} и строку {str2}")
    print(a)
    return a


M = int(input('Введите кол-во строк'))
N = int(input('Введите кол-во столбцов'))
b = np.random.random((M,N))
print(b)
change_str(b)

[[0.36482774 0.70772836]
 [0.67059391 0.21506024]
 [0.57750035 0.80474537]
 [0.81800291 0.1998362 ]
 [0.56540386 0.79024978]
 [0.26616771 0.07731791]]
Меняем строку 4 и строку 3
[[0.36482774 0.70772836]
 [0.67059391 0.21506024]
 [0.57750035 0.80474537]
 [0.56540386 0.79024978]
 [0.81800291 0.1998362 ]
 [0.26616771 0.07731791]]


array([[0.36482774, 0.70772836],
       [0.67059391, 0.21506024],
       [0.57750035, 0.80474537],
       [0.56540386, 0.79024978],
       [0.81800291, 0.1998362 ],
       [0.26616771, 0.07731791]])

**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [99]:
import numpy as np

def get_top_number(a):
    top_number = {}
    max_count = 0
    max_value = 0
    for item in a:
        if item in top_number:
            top_number[item] += 1
            if top_number[item] > max_count:
                max_count = top_number[item]
                max_value = item
        else:
            top_number.update({item:1})
    return {"value":max_value, "count":max_count}



M = int(input('Введите кол-во элементов массива'))

b = np.random.randint(0,5, size = (M))
print(b)
answer = get_top_number(b)
if answer.get('count') == 0:
    print('Все значения встречаются одинаковое количество раз')
else:
    print(answer)


[3 3 3 1 2 0 1 0 2 3]
{'value': 3, 'count': 4}


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [100]:
import numpy as np
matrix = np.random.randint(10,99,(16,16))
res=matrix.copy()
res.shape=(64, 4)
res=np.sum(res, axis=1)
res.shape=(4, 4, 4)
res=np.sum(res, axis=1)
print(res)

[[ 915  943  908  917]
 [ 873  919 1025  703]
 [ 694  814  994 1155]
 [ 873  878  777  809]]


**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [117]:
import numpy as np

def get_top_number(a, n):
    top_number = {}
    for row_item in a:
        for value in row_item:
            if value in top_number:
                top_number[value] += 1
            else:
                top_number.update({value:1})
    top_number = dict(sorted(top_number.items(), key=lambda item: item[1]))
    top_number=list(top_number)[::-1]
    top_number=top_number[:n]
    return top_number


N = np.random.randint(0,10)
M = np.random.randint(0,10)

n = int(input('Введите кол-во элементов'))

b = np.random.randint(0,5, size = (N+n, M+n))
print(b)
answer = get_top_number(b, n)
print("Числа встречающиеся чаще всего:", answer)


[[4 2 2 3 3 1]]
Числа встречающиеся чаще всего: [3]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [122]:
import numpy as np

def get_nerav(Z):
    E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
    U = Z[~E]
    return U

b = np.random.randint(0,2, size = (10,3))
print(b)
answer = get_nerav(b)
print(answer)


[[1 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]]
[[1 1 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 0]]


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```